# Base configs
#baseurl: "https://photography.e-r.me"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "***"

# UI configs
title: "Photography by Elias"
subtitle: "See the world through my eyes!"
author: "Elias"
header:
 title: "Photography"
 subtitle: "by Elias"
footer:
 name: "Hey there, my name is Elias"
 bio: ""
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  github: "https://www.github.com/"
